import {
  Customer,
  InventoryItem,
  MenuItem,
  Order,
  Outlet,
  Reservation,
  RestaurantConfig,
  RestaurantTable,
  RoomServiceOrder,
  User,
} from '../types';

export const DEMO_OUTLETS: Outlet[] = [
  {
    id: 'outlet-main',
    name: 'The Royal Pavilion (Main Dining)',
    code: 'RP-01',
    type: 'Fine Dining / All-Day',
    address: 'Lobby Level, Grand Monarch Hotel',
    tablesCount: 24,
    activeOrdersCount: 8,
    revenueToday: 142800,
  },
  {
    id: 'outlet-spice',
    name: 'Spice Orchid (Regional Specialty)',
    code: 'SO-02',
    type: 'Specialty Restaurant',
    address: '1st Floor Terrace, Grand Monarch Hotel',
    tablesCount: 16,
    activeOrdersCount: 5,
    revenueToday: 89400,
  },
  {
    id: 'outlet-pool',
    name: 'Horizon Pool Bar & Lounge',
    code: 'HP-03',
    type: 'Lounge & Quick Bites',
    address: 'Rooftop Deck, Grand Monarch Hotel',
    tablesCount: 12,
    activeOrdersCount: 3,
    revenueToday: 51200,
  },
];

export const RESTAURANT_PRESETS: Record<string, RestaurantConfig> = {
  thattukada: {
    id: 'rest-thattukada',
    name: 'Al-Madina Thattukada',
    type: 'thattukada',
    tagline: 'Authentic Street Flavors & Quick Bites',
    currency: 'INR',
    currencySymbol: '₹',
    serviceModels: ['takeaway', 'counter_service', 'dine_in'],
    staffModel: 'solo',
    enabledModules: ['dashboard', 'orders', 'menu', 'billing', 'inventory', 'reports', 'settings'],
    outlets: [
      {
        id: 'outlet-thatu',
        name: 'Town Central Stall',
        code: 'TK-01',
        type: 'Street Food Stall',
        address: 'MG Road Junction',
        tablesCount: 4,
        activeOrdersCount: 3,
        revenueToday: 18450,
      },
    ],
    currentOutletId: 'outlet-thatu',
    taxRate: 0,
    serviceChargeRate: 0,
  },
  cafe: {
    id: 'rest-cafe',
    name: 'Roast & Bloom Coffee Co.',
    type: 'cafe',
    tagline: 'Artisanal Roastery & Fresh Bakes',
    currency: 'INR',
    currencySymbol: '₹',
    serviceModels: ['dine_in', 'takeaway', 'counter_service', 'qr_ordering'],
    staffModel: 'hybrid',
    enabledModules: ['dashboard', 'pos', 'orders', 'menu', 'billing', 'inventory', 'reports', 'settings'],
    outlets: [
      {
        id: 'outlet-cafe',
        name: 'Indiranagar Flagship',
        code: 'RB-01',
        type: 'Artisan Cafe',
        address: '12th Main, Indiranagar',
        tablesCount: 10,
        activeOrdersCount: 4,
        revenueToday: 34900,
      },
    ],
    currentOutletId: 'outlet-cafe',
    taxRate: 5,
    serviceChargeRate: 5,
  },
  restaurant: {
    id: 'rest-malabar',
    name: 'Malabar Kitchen',
    type: 'restaurant',
    tagline: 'Traditional Flavors & Modern Hospitality',
    currency: 'INR',
    currencySymbol: '₹',
    serviceModels: ['dine_in', 'takeaway', 'delivery', 'table_service'],
    staffModel: 'assigned_tables',
    enabledModules: [
      'dashboard',
      'pos',
      'orders',
      'tables',
      'kitchen',
      'menu',
      'inventory',
      'customers',
      'staff',
      'billing',
      'reports',
      'settings',
    ],
    outlets: [
      {
        id: 'outlet-malabar',
        name: 'Marine Drive Branch',
        code: 'MK-01',
        type: 'Casual Dining',
        address: 'Marine Drive, Kochi',
        tablesCount: 16,
        activeOrdersCount: 7,
        revenueToday: 76500,
      },
    ],
    currentOutletId: 'outlet-malabar',
    taxRate: 5,
    serviceChargeRate: 0,
  },
  fine_dining: {
    id: 'rest-finedining',
    name: 'L’Azure Heritage',
    type: 'fine_dining',
    tagline: 'Curated Gastronomy & Sommelier Service',
    currency: 'INR',
    currencySymbol: '₹',
    serviceModels: ['dine_in', 'reservations', 'table_service'],
    staffModel: 'section_based',
    enabledModules: [
      'dashboard',
      'pos',
      'orders',
      'tables',
      'reservations',
      'kitchen',
      'menu',
      'inventory',
      'customers',
      'staff',
      'billing',
      'reports',
      'settings',
    ],
    outlets: [
      {
        id: 'outlet-azure',
        name: 'Fort Kochi Estate',
        code: 'AZ-01',
        type: 'Fine Dining Estate',
        address: 'Bazaar Road, Fort Kochi',
        tablesCount: 18,
        activeOrdersCount: 6,
        revenueToday: 122400,
      },
    ],
    currentOutletId: 'outlet-azure',
    taxRate: 18,
    serviceChargeRate: 10,
  },
  hotel_fb: {
    id: 'rest-hotel',
    name: 'The Grand Monarch Palace & Suites',
    type: 'hotel_fb',
    tagline: 'Enterprise Luxury F&B, Banquets & In-Room Dining',
    currency: 'INR',
    currencySymbol: '₹',
    serviceModels: ['dine_in', 'room_service', 'reservations', 'table_service', 'takeaway'],
    staffModel: 'section_based',
    enabledModules: [
      'dashboard',
      'outlets',
      'reservations',
      'tables',
      'orders',
      'kitchen',
      'room_service',
      'menu',
      'inventory',
      'procurement',
      'customers',
      'staff',
      'billing',
      'reports',
      'audit_logs',
      'settings',
    ],
    outlets: DEMO_OUTLETS,
    currentOutletId: 'outlet-main',
    taxRate: 18,
    serviceChargeRate: 10,
  },
  bakery: {
    id: 'rest-bakery',
    name: 'Crumb & Crust Bakehouse',
    type: 'bakery',
    tagline: 'Artisanal Sourdough, Pastries & Custom Cakes',
    currency: 'INR',
    currencySymbol: '₹',
    serviceModels: ['takeaway', 'counter_service', 'pickup'],
    staffModel: 'hybrid',
    enabledModules: ['dashboard', 'pos', 'orders', 'menu', 'billing', 'inventory', 'customers', 'reports', 'settings'],
    outlets: [
      {
        id: 'outlet-bake-1',
        name: 'Hill Road Bakehouse',
        code: 'BK-01',
        type: 'Bakery & Retail',
        address: 'Hill Road, Bandra West',
        tablesCount: 6,
        activeOrdersCount: 4,
        revenueToday: 28900,
      },
    ],
    currentOutletId: 'outlet-bake-1',
    taxRate: 5,
    serviceChargeRate: 0,
  },
  qsr: {
    id: 'rest-qsr',
    name: 'Turbo Burger & Shakes',
    type: 'qsr',
    tagline: 'High-Volume Fast Food & Speed of Service',
    currency: 'INR',
    currencySymbol: '₹',
    serviceModels: ['takeaway', 'counter_service', 'dine_in', 'delivery'],
    staffModel: 'multi_table',
    enabledModules: ['dashboard', 'pos', 'orders', 'kitchen', 'menu', 'billing', 'inventory', 'reports', 'settings'],
    outlets: [
      {
        id: 'outlet-qsr-1',
        name: 'Express Hub Station',
        code: 'TB-01',
        type: 'Quick Service Outlet',
        address: 'Metro Walkway Concours',
        tablesCount: 12,
        activeOrdersCount: 9,
        revenueToday: 64200,
      },
    ],
    currentOutletId: 'outlet-qsr-1',
    taxRate: 5,
    serviceChargeRate: 0,
  },
  cloud_kitchen: {
    id: 'rest-cloud',
    name: 'Ghost Kitchen Collective',
    type: 'cloud_kitchen',
    tagline: 'Multi-Brand Delivery & Aggregator Command Center',
    currency: 'INR',
    currencySymbol: '₹',
    serviceModels: ['delivery', 'takeaway'],
    staffModel: 'solo',
    enabledModules: ['dashboard', 'orders', 'kitchen', 'menu', 'inventory', 'reports', 'settings'],
    outlets: [
      {
        id: 'outlet-cloud-1',
        name: 'Dark Kitchen Hub #3',
        code: 'GK-03',
        type: 'Commercial Cloud Kitchen',
        address: 'Industrial Estate, Sector 4',
        tablesCount: 0,
        activeOrdersCount: 11,
        revenueToday: 58400,
      },
    ],
    currentOutletId: 'outlet-cloud-1',
    taxRate: 5,
    serviceChargeRate: 0,
  },
  multi_outlet: {
    id: 'rest-multi',
    name: 'Heritage Spice Group (Chain)',
    type: 'multi_outlet',
    tagline: 'Multi-Branch Restaurant Chain & Central Commissary',
    currency: 'INR',
    currencySymbol: '₹',
    serviceModels: ['dine_in', 'takeaway', 'delivery', 'table_service', 'reservations'],
    staffModel: 'section_based',
    enabledModules: [
      'dashboard',
      'outlets',
      'orders',
      'tables',
      'kitchen',
      'menu',
      'inventory',
      'procurement',
      'customers',
      'staff',
      'billing',
      'reports',
      'audit_logs',
      'settings',
    ],
    outlets: [
      {
        id: 'outlet-chain-1',
        name: 'Downtown Flagship',
        code: 'HG-01',
        type: 'Dining & Bar',
        address: 'MG Road Flagship',
        tablesCount: 22,
        activeOrdersCount: 8,
        revenueToday: 132000,
      },
      {
        id: 'outlet-chain-2',
        name: 'Mall Galleria Branch',
        code: 'HG-02',
        type: 'Bistro Outlet',
        address: 'Phoenix Mall 3rd Floor',
        tablesCount: 16,
        activeOrdersCount: 5,
        revenueToday: 91400,
      },
    ],
    currentOutletId: 'outlet-chain-1',
    taxRate: 5,
    serviceChargeRate: 5,
  },
};

export const DEMO_USERS: User[] = [
  {
    id: 'user-owner',
    name: 'Rahul Nair',
    email: 'rahul.owner@serveos.com',
    phone: '+91 98470 11223',
    pin: '1111',
    role: 'owner',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-manager',
    name: 'Priya Menon',
    email: 'priya.manager@serveos.com',
    phone: '+91 98471 22334',
    pin: '2222',
    role: 'manager',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-waiter',
    name: 'Vishnu K',
    email: 'vishnu.waiter@serveos.com',
    phone: '+91 98472 33445',
    pin: '3333',
    role: 'waiter',
    assignedTables: ['T01', 'T02', 'T03', 'T04', 'T05'],
    assignedSection: 'Indoor',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-chef',
    name: 'Chef Anton Cruz',
    email: 'anton.chef@serveos.com',
    phone: '+91 98473 44556',
    pin: '4444',
    role: 'chef',
    avatarUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-cashier',
    name: 'Ananya Sharma',
    email: 'ananya.cashier@serveos.com',
    phone: '+91 98474 55667',
    pin: '5555',
    role: 'cashier',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-inventory',
    name: 'Suresh Madhavan',
    email: 'suresh.stock@serveos.com',
    phone: '+91 98475 66778',
    pin: '6666',
    role: 'inventory_staff',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-fb-dir',
    name: 'Alexander Vance',
    email: 'alexander.fb@serveos.com',
    phone: '+91 98476 77889',
    pin: '7777',
    role: 'fb_director',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
];

export const DEMO_MENU_ITEMS: MenuItem[] = [
  // Thattukada & Malabar Staples
  {
    id: 'item-porotta',
    name: 'Malabar Flaky Porotta (2 pcs)',
    category: 'Breads & Rice',
    price: 60,
    description: 'Crisp, layered traditional wheat flatbread kneaded with milk.',
    isAvailable: true,
    isVeg: true,
    prepTimeMinutes: 5,
    station: 'grill',
    variants: [
      { id: 'v-reg', name: 'Classic Refined Flour', price: 60 },
      { id: 'v-wheat', name: 'Whole Wheat Special', price: 75 },
    ],
  },
  {
    id: 'item-beef-fry',
    name: 'Slow-Roasted Beef Roast (Ularthiyathu)',
    category: 'Mains',
    price: 240,
    description: 'Tender beef chunks slow-roasted with coconut slivers, curry leaves, and cracked pepper.',
    isAvailable: true,
    isVeg: false,
    prepTimeMinutes: 12,
    station: 'main',
    modifiers: [
      { id: 'm-extra-spicy', name: 'Extra Pepper Heat', price: 0 },
      { id: 'm-coconut-extra', name: 'Extra Roasted Coconut', price: 25 },
    ],
  },
  {
    id: 'item-kothu-porotta',
    name: 'Chicken Kothu Porotta',
    category: 'Mains',
    price: 210,
    description: 'Shredded flaky porotta tossed with shredded chicken, eggs, onions, and spicy salna gravy.',
    isAvailable: true,
    isVeg: false,
    prepTimeMinutes: 8,
    station: 'grill',
    variants: [
      { id: 'kp-half', name: 'Regular Portion', price: 210 },
      { id: 'kp-full', name: 'Loaded Jumbo', price: 320 },
    ],
  },
  {
    id: 'item-biryani-chick',
    name: 'Thalassery Chicken Biryani',
    category: 'Breads & Rice',
    price: 290,
    description: 'Fragrant short-grain Khaima rice slow-cooked on dum with tender spiced chicken and cashews.',
    isAvailable: true,
    isVeg: false,
    prepTimeMinutes: 10,
    station: 'main',
    modifiers: [
      { id: 'm-extra-raita', name: 'Extra Mint Raita', price: 20 },
      { id: 'm-boiled-egg', name: 'Add Spiced Boiled Egg', price: 25 },
    ],
  },
  {
    id: 'item-fish-curry',
    name: 'Alleppey Kingfish Curry',
    category: 'Mains',
    price: 360,
    description: 'Fresh sear fish simmered in raw mango, turmeric, and fresh coconut milk.',
    isAvailable: true,
    isVeg: false,
    prepTimeMinutes: 14,
    station: 'main',
  },
  {
    id: 'item-paneer-roast',
    name: 'Ghee Roasted Cottage Cheese',
    category: 'Mains',
    price: 260,
    description: 'Fresh paneer cubes tossed in fiery Kundapur red chili paste and pure clarified butter.',
    isAvailable: true,
    isVeg: true,
    prepTimeMinutes: 10,
    station: 'main',
  },
  {
    id: 'item-appam',
    name: 'Lacy Kallappam (3 pcs)',
    category: 'Breads & Rice',
    price: 70,
    description: 'Soft-centered fermented rice pancakes with crisp lacy edges.',
    isAvailable: true,
    isVeg: true,
    prepTimeMinutes: 6,
    station: 'grill',
  },
  {
    id: 'item-samosa',
    name: 'Malabar Irachi Pathiri (3 pcs)',
    category: 'Appetizers',
    price: 130,
    description: 'Crispy pastry parcels filled with fragrant spiced minced chicken.',
    isAvailable: true,
    isVeg: false,
    prepTimeMinutes: 6,
    station: 'bakery',
  },

  // Beverages & Cafe
  {
    id: 'item-sulaimani',
    name: 'Spiced Sulaimani Black Tea',
    category: 'Beverages',
    price: 35,
    description: 'Golden black tea brewed with cardamom, cloves, and a squeeze of fresh lemon.',
    isAvailable: true,
    isVeg: true,
    prepTimeMinutes: 4,
    station: 'beverage',
  },
  {
    id: 'item-kulukki',
    name: 'Kulukki Sharbath (Special Lime)',
    category: 'Beverages',
    price: 55,
    description: 'Hand-shaken sweet & sour cooler with sabja basil seeds and green bird chili.',
    isAvailable: true,
    isVeg: true,
    prepTimeMinutes: 3,
    station: 'beverage',
  },
  {
    id: 'item-espresso',
    name: 'Monsoon Malabar Single Estate Espresso',
    category: 'Beverages',
    price: 160,
    description: 'Bold double extraction with notes of dark cacao, dried figs, and roasted walnut.',
    isAvailable: true,
    isVeg: true,
    prepTimeMinutes: 4,
    station: 'beverage',
    variants: [
      { id: 'esp-single', name: 'Single Shot', price: 140 },
      { id: 'esp-double', name: 'Doppio (Double)', price: 180 },
    ],
    modifiers: [
      { id: 'm-oat', name: 'Oat Milk Sub', price: 40 },
      { id: 'm-almond', name: 'Almond Milk Sub', price: 45 },
      { id: 'm-vanilla', name: 'Madagascar Vanilla Syrup', price: 30 },
    ],
  },
  {
    id: 'item-cappuccino',
    name: 'Velvet Flat White / Cappuccino',
    category: 'Beverages',
    price: 210,
    description: 'Silky micro-foam steamed over rich espresso with latte art.',
    isAvailable: true,
    isVeg: true,
    prepTimeMinutes: 5,
    station: 'beverage',
    variants: [
      { id: 'cap-reg', name: 'Regular (8oz)', price: 210 },
      { id: 'cap-large', name: 'Grande (12oz)', price: 260 },
    ],
  },
  {
    id: 'item-croissant',
    name: 'Butter Flake Almond Croissant',
    category: 'Appetizers',
    price: 190,
    description: 'Double-baked artisan French pastry loaded with frangipane and toasted almonds.',
    isAvailable: true,
    isVeg: true,
    prepTimeMinutes: 3,
    station: 'bakery',
  },

  // Fine Dining & 5-Star Hotel Specials
  {
    id: 'item-truffle-pasta',
    name: 'Hand-Cut Tagliatelle with Black Truffle',
    category: 'Mains',
    price: 780,
    description: 'Fresh egg pasta tossed in 36-month aged Parmigiano Reggiano butter and shaved seasonal black truffle.',
    isAvailable: true,
    isVeg: true,
    prepTimeMinutes: 16,
    station: 'main',
  },
  {
    id: 'item-tenderloin',
    name: 'Sous-Vide Black Angus Tenderloin (8oz)',
    category: 'Mains',
    price: 1250,
    description: 'Grass-fed fillet with charred asparagus, potato mousseline, and bone marrow demi-glace.',
    isAvailable: true,
    isVeg: false,
    prepTimeMinutes: 22,
    station: 'grill',
    variants: [
      { id: 'doneness-rare', name: 'Medium Rare', price: 1250 },
      { id: 'doneness-med', name: 'Medium', price: 1250 },
      { id: 'doneness-well', name: 'Medium Well', price: 1250 },
    ],
  },
  {
    id: 'item-lobster',
    name: 'Pan-Seared Bay of Bengal Lobster',
    category: 'Mains',
    price: 1450,
    description: 'Butter-poached lobster tail over saffron risotto and wild fennel foam.',
    isAvailable: true,
    isVeg: false,
    prepTimeMinutes: 20,
    station: 'grill',
  },
  {
    id: 'item-club-sandwich',
    name: 'Monarch Gourmet Club Sandwich',
    category: 'Appetizers',
    price: 460,
    description: 'Triple-decker toasted brioche with smoked chicken, organic fried egg, crisp bacon, aged cheddar, and house fries.',
    isAvailable: true,
    isVeg: false,
    prepTimeMinutes: 12,
    station: 'main',
  },
  {
    id: 'item-payasam',
    name: 'Ada Pradhaman (Jaggery Pudding)',
    category: 'Desserts',
    price: 160,
    description: 'Steamed rice pastry flakes simmered in rich jaggery syrup and roasted coconut milk.',
    isAvailable: true,
    isVeg: true,
    prepTimeMinutes: 5,
    station: 'dessert',
  },
  {
    id: 'item-tiramisu',
    name: 'Savoiardi Espresso Tiramisù',
    category: 'Desserts',
    price: 340,
    description: 'Mascarpone cream infused with dark roast coffee and Valrhona cocoa dust.',
    isAvailable: true,
    isVeg: true,
    prepTimeMinutes: 5,
    station: 'dessert',
  },
];

export const DEMO_TABLES: RestaurantTable[] = [
  {
    id: 'tbl-01',
    tableNumber: 'T01',
    capacity: 2,
    status: 'billing',
    section: 'Indoor',
    assignedStaffId: 'user-waiter',
    assignedStaffName: 'Vishnu K',
    currentOrderId: 'ord-101',
    currentOrderAmount: 490,
    guestCount: 2,
    elapsedMinutes: 42,
    outletId: 'outlet-malabar',
  },
  {
    id: 'tbl-02',
    tableNumber: 'T02',
    capacity: 4,
    status: 'occupied',
    section: 'Indoor',
    assignedStaffId: 'user-waiter',
    assignedStaffName: 'Vishnu K',
    currentOrderId: 'ord-102',
    currentOrderAmount: 1280,
    guestCount: 4,
    elapsedMinutes: 28,
    outletId: 'outlet-malabar',
  },
  {
    id: 'tbl-03',
    tableNumber: 'T03',
    capacity: 2,
    status: 'billing',
    section: 'Indoor',
    assignedStaffId: 'user-waiter',
    assignedStaffName: 'Vishnu K',
    currentOrderId: 'ord-103',
    currentOrderAmount: 620,
    guestCount: 2,
    elapsedMinutes: 38,
    outletId: 'outlet-malabar',
  },
  {
    id: 'tbl-04',
    tableNumber: 'T04',
    capacity: 4,
    status: 'occupied',
    section: 'Indoor',
    assignedStaffId: 'user-waiter',
    assignedStaffName: 'Vishnu K',
    currentOrderId: 'ord-104',
    currentOrderAmount: 830,
    guestCount: 3,
    elapsedMinutes: 14,
    outletId: 'outlet-malabar',
  },
  {
    id: 'tbl-05',
    tableNumber: 'T05',
    capacity: 6,
    status: 'available',
    section: 'Family',
    assignedStaffId: 'user-waiter',
    assignedStaffName: 'Vishnu K',
    outletId: 'outlet-malabar',
  },
  {
    id: 'tbl-06',
    tableNumber: 'T06',
    capacity: 4,
    status: 'reserved',
    section: 'Outdoor',
    outletId: 'outlet-malabar',
  },
  {
    id: 'tbl-07',
    tableNumber: 'T07',
    capacity: 2,
    status: 'available',
    section: 'Outdoor',
    outletId: 'outlet-malabar',
  },
  {
    id: 'tbl-08',
    tableNumber: 'T08',
    capacity: 4,
    status: 'cleaning',
    section: 'Outdoor',
    outletId: 'outlet-malabar',
  },
  {
    id: 'tbl-09',
    tableNumber: 'VIP-01',
    capacity: 8,
    status: 'occupied',
    section: 'VIP',
    currentOrderId: 'ord-105',
    currentOrderAmount: 3450,
    guestCount: 6,
    elapsedMinutes: 55,
    outletId: 'outlet-malabar',
  },
  {
    id: 'tbl-10',
    tableNumber: 'PDR-01',
    capacity: 12,
    status: 'reserved',
    section: 'Private Dining',
    outletId: 'outlet-malabar',
  },
  {
    id: 'tbl-11',
    tableNumber: 'T11',
    capacity: 2,
    status: 'available',
    section: 'Indoor',
    outletId: 'outlet-malabar',
  },
  {
    id: 'tbl-12',
    tableNumber: 'T12',
    capacity: 4,
    status: 'available',
    section: 'Indoor',
    outletId: 'outlet-malabar',
  },
];

export const DEMO_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNumber: '#MK-101',
    orderType: 'dine_in',
    tableNumber: 'T01',
    guestCount: 2,
    status: 'billing_requested',
    subtotal: 466.67,
    taxAmount: 23.33,
    discountAmount: 0,
    totalAmount: 490,
    waiterId: 'user-waiter',
    waiterName: 'Vishnu K',
    outletId: 'outlet-malabar',
    createdAt: '2026-09-16T12:05:00',
    updatedAt: '2026-09-16T12:47:00',
    elapsedMinutes: 42,
    isPaid: false,
    items: [
      {
        id: 'oi-1',
        menuItemId: 'item-kothu-porotta',
        name: 'Chicken Kothu Porotta',
        unitPrice: 210,
        quantity: 2,
        station: 'grill',
        status: 'served',
      },
      {
        id: 'oi-2',
        menuItemId: 'item-sulaimani',
        name: 'Spiced Sulaimani Black Tea',
        unitPrice: 35,
        quantity: 2,
        station: 'beverage',
        status: 'served',
      },
    ],
  },
  {
    id: 'ord-102',
    orderNumber: '#MK-102',
    orderType: 'dine_in',
    tableNumber: 'T02',
    guestCount: 4,
    status: 'preparing',
    subtotal: 1219.05,
    taxAmount: 60.95,
    discountAmount: 0,
    totalAmount: 1280,
    waiterId: 'user-waiter',
    waiterName: 'Vishnu K',
    outletId: 'outlet-malabar',
    createdAt: '2026-09-16T12:20:00',
    updatedAt: '2026-09-16T12:35:00',
    elapsedMinutes: 28,
    isPaid: false,
    items: [
      {
        id: 'oi-3',
        menuItemId: 'item-biryani-chick',
        name: 'Thalassery Chicken Biryani',
        unitPrice: 290,
        quantity: 3,
        station: 'main',
        status: 'preparing',
        notes: 'Less chili for children',
      },
      {
        id: 'oi-4',
        menuItemId: 'item-beef-fry',
        name: 'Slow-Roasted Beef Roast (Ularthiyathu)',
        unitPrice: 240,
        quantity: 1,
        station: 'main',
        status: 'preparing',
      },
      {
        id: 'oi-5',
        menuItemId: 'item-porotta',
        name: 'Malabar Flaky Porotta (2 pcs)',
        unitPrice: 60,
        quantity: 2,
        station: 'grill',
        status: 'ready',
      },
      {
        id: 'oi-6',
        menuItemId: 'item-kulukki',
        name: 'Kulukki Sharbath (Special Lime)',
        unitPrice: 55,
        quantity: 2,
        station: 'beverage',
        status: 'served',
      },
    ],
  },
  {
    id: 'ord-103',
    orderNumber: '#MK-103',
    orderType: 'dine_in',
    tableNumber: 'T03',
    guestCount: 2,
    status: 'billing_requested',
    subtotal: 590.48,
    taxAmount: 29.52,
    discountAmount: 0,
    totalAmount: 620,
    waiterId: 'user-waiter',
    waiterName: 'Vishnu K',
    outletId: 'outlet-malabar',
    createdAt: '2026-09-16T12:12:00',
    updatedAt: '2026-09-16T12:50:00',
    elapsedMinutes: 38,
    isPaid: false,
    items: [
      {
        id: 'oi-7',
        menuItemId: 'item-fish-curry',
        name: 'Alleppey Kingfish Curry',
        unitPrice: 360,
        quantity: 1,
        station: 'main',
        status: 'served',
      },
      {
        id: 'oi-8',
        menuItemId: 'item-appam',
        name: 'Lacy Kallappam (3 pcs)',
        unitPrice: 70,
        quantity: 2,
        station: 'grill',
        status: 'served',
      },
      {
        id: 'oi-9',
        menuItemId: 'item-payasam',
        name: 'Ada Pradhaman (Jaggery Pudding)',
        unitPrice: 160,
        quantity: 1,
        station: 'dessert',
        status: 'served',
      },
    ],
  },
  {
    id: 'ord-104',
    orderNumber: '#MK-104',
    orderType: 'dine_in',
    tableNumber: 'T04',
    guestCount: 3,
    status: 'preparing',
    subtotal: 790.48,
    taxAmount: 39.52,
    discountAmount: 0,
    totalAmount: 830,
    waiterId: 'user-waiter',
    waiterName: 'Vishnu K',
    outletId: 'outlet-malabar',
    createdAt: '2026-09-16T12:34:00',
    updatedAt: '2026-09-16T12:40:00',
    elapsedMinutes: 14,
    isPaid: false,
    items: [
      {
        id: 'oi-10',
        menuItemId: 'item-biryani-chick',
        name: 'Thalassery Chicken Biryani',
        unitPrice: 290,
        quantity: 2,
        station: 'main',
        status: 'preparing',
        notes: 'Extra raita with both bowls',
      },
      {
        id: 'oi-11',
        menuItemId: 'item-beef-fry',
        name: 'Slow-Roasted Beef Roast (Ularthiyathu)',
        unitPrice: 240,
        quantity: 1,
        station: 'main',
        status: 'preparing',
      },
      {
        id: 'oi-12',
        menuItemId: 'item-porotta',
        name: 'Malabar Flaky Porotta (2 pcs)',
        unitPrice: 60,
        quantity: 1,
        station: 'grill',
        status: 'preparing',
      },
    ],
  },
  {
    id: 'ord-105',
    orderNumber: '#MK-105',
    orderType: 'dine_in',
    tableNumber: 'VIP-01',
    guestCount: 6,
    status: 'preparing',
    subtotal: 3285.71,
    taxAmount: 164.29,
    discountAmount: 0,
    totalAmount: 3450,
    outletId: 'outlet-malabar',
    createdAt: '2026-09-16T12:00:00',
    updatedAt: '2026-09-16T12:45:00',
    elapsedMinutes: 55,
    isPaid: false,
    items: [
      {
        id: 'oi-13',
        menuItemId: 'item-lobster',
        name: 'Pan-Seared Bay of Bengal Lobster',
        unitPrice: 1450,
        quantity: 2,
        station: 'grill',
        status: 'preparing',
      },
      {
        id: 'oi-14',
        menuItemId: 'item-truffle-pasta',
        name: 'Hand-Cut Tagliatelle with Black Truffle',
        unitPrice: 780,
        quantity: 1,
        station: 'main',
        status: 'ready',
      },
    ],
  },
  {
    id: 'ord-tk-88',
    orderNumber: '#TK-108',
    orderType: 'takeaway',
    guestName: 'Kiran Raj',
    guestPhone: '+91 94471 88990',
    status: 'ready',
    subtotal: 390.48,
    taxAmount: 19.52,
    discountAmount: 0,
    totalAmount: 410,
    outletId: 'outlet-malabar',
    createdAt: '2026-09-16T12:30:00',
    updatedAt: '2026-09-16T12:45:00',
    elapsedMinutes: 18,
    isPaid: true,
    paymentMethod: 'upi',
    items: [
      {
        id: 'oi-15',
        menuItemId: 'item-biryani-chick',
        name: 'Thalassery Chicken Biryani',
        unitPrice: 290,
        quantity: 1,
        station: 'main',
        status: 'ready',
      },
      {
        id: 'oi-16',
        menuItemId: 'item-samosa',
        name: 'Malabar Irachi Pathiri (3 pcs)',
        unitPrice: 130,
        quantity: 1,
        station: 'bakery',
        status: 'ready',
      },
    ],
  },
  {
    id: 'ord-room-1204',
    orderNumber: '#RS-1204',
    orderType: 'room_service',
    roomNumber: '1204',
    guestName: 'Mr. Arun Kumar',
    status: 'preparing',
    subtotal: 920.0,
    taxAmount: 165.6,
    discountAmount: 0,
    totalAmount: 1085.6,
    outletId: 'outlet-main',
    createdAt: '2026-09-16T12:28:00',
    updatedAt: '2026-09-16T12:38:00',
    elapsedMinutes: 20,
    isPaid: false,
    items: [
      {
        id: 'oi-17',
        menuItemId: 'item-cappuccino',
        name: 'Velvet Flat White / Cappuccino',
        unitPrice: 210,
        quantity: 2,
        station: 'beverage',
        status: 'ready',
      },
      {
        id: 'oi-18',
        menuItemId: 'item-club-sandwich',
        name: 'Monarch Gourmet Club Sandwich',
        unitPrice: 460,
        quantity: 1,
        station: 'main',
        status: 'preparing',
        notes: 'No mayonnaise, toasted golden',
      },
    ],
  },
];

export const DEMO_ROOM_SERVICE: RoomServiceOrder[] = [
  {
    id: 'rs-1',
    roomNumber: '1204',
    guestName: 'Mr. Arun Kumar',
    orderId: 'ord-room-1204',
    orderNumber: '#RS-1204',
    status: 'preparing',
    totalAmount: 1085.6,
    deliveryTimeEstimated: '13:10 PM',
    chargedToFolio: true,
  },
  {
    id: 'rs-2',
    roomNumber: '802',
    guestName: 'Ms. Elena Rostova',
    orderId: 'ord-room-802',
    orderNumber: '#RS-802',
    status: 'delivering',
    totalAmount: 1640.0,
    deliveryTimeEstimated: '13:00 PM',
    chargedToFolio: true,
  },
  {
    id: 'rs-3',
    roomNumber: '1501 (Presidential)',
    guestName: 'Dr. Tariq Al-Mansoor',
    orderId: 'ord-room-1501',
    orderNumber: '#RS-1501',
    status: 'delivered',
    totalAmount: 3250.0,
    deliveryTimeEstimated: '12:30 PM',
    chargedToFolio: true,
  },
];

export const DEMO_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Fresh Farm Chicken',
    category: 'meat',
    currentStock: 4.5,
    unit: 'kg',
    minThreshold: 10,
    costPerUnit: 220,
    lastRestocked: '2026-09-15',
    supplierName: 'Kochi Fresh Meats',
    status: 'low_stock',
  },
  {
    id: 'inv-2',
    name: 'Jeerakasala / Khaima Biryani Rice',
    category: 'ingredients',
    currentStock: 48,
    unit: 'kg',
    minThreshold: 20,
    costPerUnit: 140,
    lastRestocked: '2026-09-14',
    supplierName: 'Wayanad Agro Producers',
    status: 'in_stock',
  },
  {
    id: 'inv-3',
    name: 'Pure Cold-Pressed Coconut Oil',
    category: 'ingredients',
    currentStock: 2.0,
    unit: 'L',
    minThreshold: 8,
    costPerUnit: 280,
    lastRestocked: '2026-09-13',
    supplierName: 'Kerala Organic Mills',
    status: 'low_stock',
  },
  {
    id: 'inv-4',
    name: 'Full Cream Milk',
    category: 'dairy',
    currentStock: 18,
    unit: 'L',
    minThreshold: 12,
    costPerUnit: 56,
    lastRestocked: '2026-09-16',
    supplierName: 'Milma Dairy',
    status: 'in_stock',
  },
  {
    id: 'inv-5',
    name: 'Monsoon Malabar Coffee Beans',
    category: 'beverage',
    currentStock: 1.2,
    unit: 'kg',
    minThreshold: 5,
    costPerUnit: 980,
    lastRestocked: '2026-09-12',
    supplierName: 'Coorg Bean Roasters',
    status: 'low_stock',
  },
  {
    id: 'inv-6',
    name: 'Kraft Eco Meal Delivery Boxes',
    category: 'packaging',
    currentStock: 180,
    unit: 'pcs',
    minThreshold: 100,
    costPerUnit: 12,
    lastRestocked: '2026-09-10',
    supplierName: 'GreenPack Solutions',
    status: 'in_stock',
  },
  {
    id: 'inv-7',
    name: 'Fresh Kingfish (Seer)',
    category: 'meat',
    currentStock: 0.0,
    unit: 'kg',
    minThreshold: 5,
    costPerUnit: 680,
    lastRestocked: '2026-09-14',
    supplierName: 'Munambam Harbor Fish',
    status: 'out_of_stock',
  },
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Thomas Kurian',
    phone: '+91 98460 22334',
    email: 't.kurian@techcorp.com',
    totalVisits: 14,
    totalSpent: 18450,
    loyaltyPoints: 480,
    favoriteItems: ['Thalassery Chicken Biryani', 'Ada Pradhaman'],
    preferences: 'Prefers quiet corner tables in Indoor AC section.',
    vipTier: 'Gold',
    lastVisit: '2026-09-14',
  },
  {
    id: 'cust-2',
    name: 'Dr. Reshma Jacob',
    phone: '+91 94470 55667',
    email: 'dr.reshma@aims.edu',
    totalVisits: 8,
    totalSpent: 11200,
    loyaltyPoints: 260,
    favoriteItems: ['Alleppey Kingfish Curry', 'Lacy Kallappam'],
    preferences: 'Mild chili spice, extra lime wedges.',
    vipTier: 'Silver',
    lastVisit: '2026-09-12',
  },
  {
    id: 'cust-3',
    name: 'Mr. Arun Kumar',
    phone: '+91 98110 33441',
    email: 'arunkumar@luxuryventures.in',
    totalVisits: 22,
    totalSpent: 48900,
    loyaltyPoints: 1240,
    favoriteItems: ['Sous-Vide Black Angus Tenderloin', 'Monsoon Malabar Single Estate Espresso'],
    preferences: 'Executive Suite 1204 guest. VIP protocol.',
    vipTier: 'Platinum',
    lastVisit: '2026-09-16',
  },
];

export const DEMO_RESERVATIONS: Reservation[] = [
  {
    id: 'res-1',
    guestName: 'Rajeev & Anita Nambiar',
    guestPhone: '+91 98470 99887',
    guestCount: 4,
    date: '2026-09-16',
    time: '19:30',
    tableNumber: 'T06',
    status: 'confirmed',
    specialRequests: '25th Wedding Anniversary - quiet table requested.',
    outletId: 'outlet-malabar',
  },
  {
    id: 'res-2',
    guestName: 'Harish Babu Corporate Dinner',
    guestPhone: '+91 99950 11223',
    guestCount: 12,
    date: '2026-09-16',
    time: '20:00',
    tableNumber: 'PDR-01',
    status: 'confirmed',
    specialRequests: 'Fixed 4-course executive menu setup.',
    outletId: 'outlet-malabar',
  },
  {
    id: 'res-3',
    guestName: 'Meera Varma',
    guestPhone: '+91 98471 66554',
    guestCount: 2,
    date: '2026-09-16',
    time: '20:30',
    status: 'waitlist',
    specialRequests: 'Window table if possible.',
    outletId: 'outlet-malabar',
  },
];
