import { ModuleId, Permission, RestaurantType, Role } from '../../types';

export interface ModuleDefinition {
  id: ModuleId;
  label: string;
  description: string;
  category: 'core' | 'operations' | 'management' | 'enterprise';
  icon: string;
  path: string;
}

export const ALL_MODULES: Record<ModuleId, ModuleDefinition> = {
  dashboard: {
    id: 'dashboard',
    label: 'Home',
    description: 'Personalized role-based workspace and business overview',
    category: 'core',
    icon: 'LayoutDashboard',
    path: '/dashboard',
  },
  pos: {
    id: 'pos',
    label: 'Point of Sale',
    description: 'Fast counter & table order creation with instant dispatch',
    category: 'core',
    icon: 'Calculator',
    path: '/pos',
  },
  orders: {
    id: 'orders',
    label: 'Live Orders',
    description: 'Track, filter, and manage real-time active customer tickets',
    category: 'operations',
    icon: 'ShoppingBag',
    path: '/orders',
  },
  tables: {
    id: 'tables',
    label: 'Tables & Floor',
    description: 'Interactive floor plan, occupancy status, sections & table transfers',
    category: 'operations',
    icon: 'Grid3X3',
    path: '/tables',
  },
  kitchen: {
    id: 'kitchen',
    label: 'Kitchen Display',
    description: 'Multi-station KDS with prep timers, modifier cues & ready flags',
    category: 'operations',
    icon: 'ChefHat',
    path: '/kitchen',
  },
  billing: {
    id: 'billing',
    label: 'Cashier & Bills',
    description: 'Pending receipts, split bills, taxes, UPI, Card and Cash settlement',
    category: 'operations',
    icon: 'Receipt',
    path: '/billing',
  },
  menu: {
    id: 'menu',
    label: 'Menu Catalog',
    description: 'Categories, pricing, variants, add-ons, 86-list & prep times',
    category: 'management',
    icon: 'UtensilsCrossed',
    path: '/menu',
  },
  inventory: {
    id: 'inventory',
    label: 'Stock & Inventory',
    description: 'Stock levels, automatic threshold warnings, wastage and units',
    category: 'management',
    icon: 'Boxes',
    path: '/inventory',
  },
  reservations: {
    id: 'reservations',
    label: 'Reservations',
    description: 'Table bookings, guest arrival times, waitlist and party sizes',
    category: 'operations',
    icon: 'CalendarDays',
    path: '/reservations',
  },
  room_service: {
    id: 'room_service',
    label: 'Room Service',
    description: 'In-room guest dining, room folio billing, and delivery tracking',
    category: 'enterprise',
    icon: 'BedDouble',
    path: '/room-service',
  },
  customers: {
    id: 'customers',
    label: 'Customer CRM',
    description: 'Guest history, preferences, VIP tiers, and loyalty points',
    category: 'management',
    icon: 'Users',
    path: '/customers',
  },
  staff: {
    id: 'staff',
    label: 'Staff & Shifts',
    description: 'Role access, shift scheduling, table and section assignments',
    category: 'management',
    icon: 'UserCheck',
    path: '/staff',
  },
  procurement: {
    id: 'procurement',
    label: 'Procurement',
    description: 'Supplier purchase orders, deliveries and cost invoices',
    category: 'enterprise',
    icon: 'Truck',
    path: '/procurement',
  },
  reports: {
    id: 'reports',
    label: 'Reports & Sales',
    description: 'Revenue analysis, hourly volume, product performance and taxes',
    category: 'management',
    icon: 'BarChart3',
    path: '/reports',
  },
  outlets: {
    id: 'outlets',
    label: 'F&B Outlets',
    description: 'Central multi-outlet hierarchy and venue-specific metrics',
    category: 'enterprise',
    icon: 'Building2',
    path: '/outlets',
  },
  audit_logs: {
    id: 'audit_logs',
    label: 'Audit Trail',
    description: 'High-security event logs, voids, cash drawer opens and approvals',
    category: 'enterprise',
    icon: 'ShieldCheck',
    path: '/audit-logs',
  },
  settings: {
    id: 'settings',
    label: 'Settings & Modules',
    description: 'Configure restaurant parameters, taxes, and enabled modules',
    category: 'core',
    icon: 'SlidersHorizontal',
    path: '/settings',
  },
};

export const DEFAULT_MODULES_BY_TYPE: Record<RestaurantType, ModuleId[]> = {
  thattukada: ['dashboard', 'orders', 'menu', 'billing', 'inventory', 'reports', 'settings'],
  cafe: ['dashboard', 'pos', 'orders', 'menu', 'billing', 'inventory', 'reports', 'settings'],
  bakery: ['dashboard', 'pos', 'orders', 'menu', 'billing', 'inventory', 'reports', 'settings'],
  qsr: ['dashboard', 'pos', 'orders', 'kitchen', 'menu', 'billing', 'inventory', 'reports', 'settings'],
  restaurant: [
    'dashboard',
    'pos',
    'orders',
    'tables',
    'kitchen',
    'menu',
    'inventory',
    'customers',
    'staff',
    'billing',
    'reports',
    'settings',
  ],
  fine_dining: [
    'dashboard',
    'pos',
    'orders',
    'tables',
    'reservations',
    'kitchen',
    'menu',
    'inventory',
    'customers',
    'staff',
    'billing',
    'reports',
    'settings',
  ],
  cloud_kitchen: [
    'dashboard',
    'orders',
    'kitchen',
    'menu',
    'inventory',
    'procurement',
    'reports',
    'settings',
  ],
  hotel_fb: [
    'dashboard',
    'outlets',
    'reservations',
    'tables',
    'orders',
    'kitchen',
    'room_service',
    'menu',
    'inventory',
    'procurement',
    'customers',
    'staff',
    'billing',
    'reports',
    'audit_logs',
    'settings',
  ],
  multi_outlet: [
    'dashboard',
    'outlets',
    'orders',
    'tables',
    'kitchen',
    'menu',
    'inventory',
    'procurement',
    'customers',
    'staff',
    'billing',
    'reports',
    'audit_logs',
    'settings',
  ],
};

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  owner: [
    'view_dashboard',
    'create_order',
    'view_orders',
    'cancel_order',
    'view_tables',
    'manage_tables',
    'view_kitchen',
    'update_kitchen_status',
    'manage_billing',
    'process_payment',
    'issue_refund',
    'manage_menu',
    'view_inventory',
    'adjust_stock',
    'manage_staff',
    'view_reports',
    'view_finance',
    'manage_reservations',
    'manage_room_service',
    'manage_modules',
    'manage_outlets',
  ],
  admin: [
    'view_dashboard',
    'create_order',
    'view_orders',
    'cancel_order',
    'view_tables',
    'manage_tables',
    'view_kitchen',
    'update_kitchen_status',
    'manage_billing',
    'process_payment',
    'issue_refund',
    'manage_menu',
    'view_inventory',
    'adjust_stock',
    'manage_staff',
    'view_reports',
    'manage_reservations',
    'manage_room_service',
    'manage_modules',
    'manage_outlets',
  ],
  manager: [
    'view_dashboard',
    'create_order',
    'view_orders',
    'cancel_order',
    'view_tables',
    'manage_tables',
    'view_kitchen',
    'manage_billing',
    'process_payment',
    'manage_menu',
    'view_inventory',
    'adjust_stock',
    'manage_staff',
    'view_reports',
    'manage_reservations',
    'manage_room_service',
  ],
  fb_director: [
    'view_dashboard',
    'view_orders',
    'view_tables',
    'view_kitchen',
    'view_inventory',
    'manage_staff',
    'view_reports',
    'view_finance',
    'manage_outlets',
    'manage_reservations',
    'manage_room_service',
  ],
  waiter: [
    'view_dashboard',
    'create_order',
    'view_orders',
    'view_tables',
    'manage_tables',
    'manage_reservations',
  ],
  cashier: [
    'view_dashboard',
    'view_orders',
    'manage_billing',
    'process_payment',
    'view_tables',
  ],
  chef: [
    'view_dashboard',
    'view_kitchen',
    'update_kitchen_status',
    'view_orders',
    'manage_menu',
  ],
  kitchen_staff: [
    'view_kitchen',
    'update_kitchen_status',
  ],
  inventory_staff: [
    'view_dashboard',
    'view_inventory',
    'adjust_stock',
  ],
  inventory_manager: [
    'view_dashboard',
    'view_inventory',
    'adjust_stock',
    'view_reports',
    'manage_menu',
  ],
  restaurant_manager: [
    'view_dashboard',
    'create_order',
    'view_orders',
    'cancel_order',
    'view_tables',
    'manage_tables',
    'view_kitchen',
    'manage_billing',
    'process_payment',
    'manage_menu',
    'view_inventory',
    'adjust_stock',
    'manage_staff',
    'view_reports',
    'manage_reservations',
    'manage_room_service',
  ],
  captain: [
    'view_dashboard',
    'create_order',
    'view_orders',
    'view_tables',
    'manage_tables',
    'manage_reservations',
    'manage_billing',
  ],
  steward: [
    'view_tables',
    'manage_tables',
    'view_orders',
  ],
  billing_staff: [
    'view_dashboard',
    'view_orders',
    'manage_billing',
    'process_payment',
    'create_order',
  ],
  sous_chef: [
    'view_kitchen',
    'update_kitchen_status',
    'view_orders',
    'manage_menu',
    'view_inventory',
  ],
  barista: [
    'view_kitchen',
    'update_kitchen_status',
    'view_orders',
  ],
  staff: [
    'view_orders',
    'create_order',
    'view_kitchen',
    'update_kitchen_status',
  ],
  accountant: [
    'view_dashboard',
    'view_orders',
    'manage_billing',
    'view_reports',
    'view_finance',
  ],
};

// Determines whether a role is allowed to see a particular module
export const ROLE_ALLOWED_MODULES: Record<Role, ModuleId[]> = {
  owner: [
    'dashboard',
    'pos',
    'orders',
    'tables',
    'reservations',
    'kitchen',
    'billing',
    'menu',
    'inventory',
    'customers',
    'staff',
    'room_service',
    'procurement',
    'reports',
    'outlets',
    'audit_logs',
    'settings',
  ],
  admin: [
    'dashboard',
    'pos',
    'orders',
    'tables',
    'reservations',
    'kitchen',
    'billing',
    'menu',
    'inventory',
    'customers',
    'staff',
    'room_service',
    'procurement',
    'reports',
    'outlets',
    'settings',
  ],
  manager: [
    'dashboard',
    'pos',
    'orders',
    'tables',
    'reservations',
    'kitchen',
    'billing',
    'menu',
    'inventory',
    'customers',
    'staff',
    'room_service',
    'reports',
    'settings',
  ],
  restaurant_manager: [
    'dashboard',
    'pos',
    'orders',
    'tables',
    'reservations',
    'kitchen',
    'billing',
    'menu',
    'inventory',
    'customers',
    'staff',
    'room_service',
    'reports',
    'settings',
  ],
  fb_director: [
    'dashboard',
    'outlets',
    'reports',
    'orders',
    'tables',
    'reservations',
    'room_service',
    'menu',
    'inventory',
    'procurement',
    'staff',
    'audit_logs',
    'settings',
  ],
  waiter: ['dashboard', 'tables', 'orders', 'billing', 'pos'],
  captain: ['dashboard', 'tables', 'orders', 'billing', 'pos', 'reservations'],
  steward: ['tables', 'orders'],
  cashier: ['dashboard', 'billing', 'orders', 'tables', 'pos'],
  billing_staff: ['dashboard', 'billing', 'orders', 'pos'],
  chef: ['kitchen', 'orders', 'menu', 'dashboard'],
  sous_chef: ['kitchen', 'orders', 'menu', 'inventory'],
  barista: ['kitchen', 'orders'],
  kitchen_staff: ['kitchen', 'orders'],
  staff: ['orders', 'kitchen', 'billing'],
  inventory_staff: ['dashboard', 'inventory', 'procurement', 'reports'],
  inventory_manager: ['dashboard', 'inventory', 'procurement', 'reports', 'menu'],
  accountant: ['dashboard', 'billing', 'reports', 'audit_logs', 'orders'],
};

export const ALL_MODULE_DEFINITIONS: ModuleDefinition[] = Object.values(ALL_MODULES);
